import Head from "next/head";
import styles from "@styles/Home.module.css";
import NavBar from "@components/NavBar/NavBar.js";
import AuthButton from "@components/AuthButton/AuthButton.js";

export default function Home() {
	return (
		<>
			<Head>
				<title>qord App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<header className={styles.header}>
				<NavBar showAuthLinks={true} />
			</header>
			<main className={styles.main}>
				<div className={styles.hero__container}>
					<h1 className={styles.hero_maintitle}>qord: Your Melodic Compass </h1>
					<h2 className={styles.hero__subtitle}>
						Navigate Melodies with Just a Tonic <br /> and Mode Selection
					</h2>
					<AuthButton href="/register">SignUp</AuthButton>
				</div>
			</main>
		</>
	);
}
